// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDj52lcW_HGdXN8k5QR9DIlMuJoHX9Njo8',
    appId: '1:601027321675:web:a11270c371ca68f28b92ce',
    messagingSenderId: '601027321675',
    projectId: 'flutter-project-eb474',
    authDomain: 'flutter-project-eb474.firebaseapp.com',
    storageBucket: 'flutter-project-eb474.firebasestorage.app',
    measurementId: 'G-ZZ7F213JX5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGSVN3U0-hhvefUMPWENN7Lt8ypkzAXAg',
    appId: '1:601027321675:android:b66522857fb4a2428b92ce',
    messagingSenderId: '601027321675',
    projectId: 'flutter-project-eb474',
    storageBucket: 'flutter-project-eb474.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC84_BoR4LmgzWuHYJn1ZixW_NE985rnyw',
    appId: '1:601027321675:ios:f54dc593286390bb8b92ce',
    messagingSenderId: '601027321675',
    projectId: 'flutter-project-eb474',
    storageBucket: 'flutter-project-eb474.firebasestorage.app',
    iosBundleId: 'com.example.p7',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC84_BoR4LmgzWuHYJn1ZixW_NE985rnyw',
    appId: '1:601027321675:ios:f54dc593286390bb8b92ce',
    messagingSenderId: '601027321675',
    projectId: 'flutter-project-eb474',
    storageBucket: 'flutter-project-eb474.firebasestorage.app',
    iosBundleId: 'com.example.p7',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDj52lcW_HGdXN8k5QR9DIlMuJoHX9Njo8',
    appId: '1:601027321675:web:b6b515d1fee8196c8b92ce',
    messagingSenderId: '601027321675',
    projectId: 'flutter-project-eb474',
    authDomain: 'flutter-project-eb474.firebaseapp.com',
    storageBucket: 'flutter-project-eb474.firebasestorage.app',
    measurementId: 'G-6C80KYZQCP',
  );
}
